---
name: Sistemas de numeración
locale: es
type: practice
beta: false
teacher_info: ''
language: text
id_format: '%05d'
order:
- 9
- 1
- 2
- 3
- 4
- 11
- 12
- 14
- 5
- 7
- 13
- 16
- 15
- 8
- 6
- 10
- 17
